let
    Source = Excel.Workbook(File.Contents("C:\Users\saqla\Downloads\PowerBI Test-1 (1).xlsx"), null, true),
    #"Raw Data_Sheet" = Source{[Item="Raw Data",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Raw Data_Sheet", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sr. No.", Int64.Type}, {"Completion Date", type text}, {"Request Type", type text}, {"Request Sub-Type", type text}, {"Language Type", type text}, {"Batch Sr. No.", Int64.Type}, {"Date of Receipt", type date}, {"SOA/SOW/MOU", type text}, {"Language", type text}, {"Sweden/Norway/No", type text}, {"Upload/Abstract Date", type any}, {"Column12", type any}, {"Column13", type any}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column12", "Column13"}),
    #"Removed Blank Rows" = Table.SelectRows(#"Removed Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Removed Duplicates" = Table.Distinct(#"Removed Blank Rows", {"Sr. No."}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates","-",null,Replacer.ReplaceValue,{"Upload/Abstract Date"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","NA",null,Replacer.ReplaceValue,{"Sweden/Norway/No"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","-",null,Replacer.ReplaceValue,{"Request Type", "Request Sub-Type"}),
    #"Filtered Rows" = Table.SelectRows(#"Replaced Value2", each ([Completion Date] <> null)),
    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Completion Date Only", each Text.BeforeDelimiter(Text.Range([Completion Date], 4), " ")),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"Sr. No.", "Completion Date", "Completion Date Only", "Request Type", "Request Sub-Type", "Language Type", "Batch Sr. No.", "Date of Receipt", "SOA/SOW/MOU", "Language", "Sweden/Norway/No", "Upload/Abstract Date"}),
    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Reordered Columns", {{"Completion Date Only", type date}}, "en-US"),
    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"Upload/Abstract Date", type date}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type2", "TAT in Days", each [Completion Date Only]-[#"Upload/Abstract Date"]),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom1",{{"TAT in Days", Int64.Type}}),
    #"Added Custom2" = Table.AddColumn(#"Changed Type3", "Matchkey", each [Request Type]&"_"&[Language Type]),
    #"Merged Queries" = Table.NestedJoin(#"Added Custom2", {"Matchkey"}, Pricing, {"MatchKey"}, "Pricing", JoinKind.LeftOuter),
    #"Expanded Pricing" = Table.ExpandTableColumn(#"Merged Queries", "Pricing", {"Rate per unit"}, {"Pricing.Rate per unit"}),
    #"Added Custom3" = Table.AddColumn(#"Expanded Pricing", "SLA_met", each try if [TAT in Days] < 2 then "Compliant" else "Non-Compliant" otherwise null),
    #"Filtered Rows1" = Table.SelectRows(#"Added Custom3", each ([TAT in Days] <> -140)),
    #"Inserted Month" = Table.AddColumn(#"Filtered Rows1", "Month", each Date.Month([Completion Date Only]), Int64.Type),
    #"Renamed Columns" = Table.RenameColumns(#"Inserted Month",{{"Month", "Completion_Month"}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns",{"Sr. No.", "Completion Date", "Completion Date Only", "Completion_Month", "Request Type", "Request Sub-Type", "Language Type", "Batch Sr. No.", "Date of Receipt", "SOA/SOW/MOU", "Language", "Sweden/Norway/No", "Upload/Abstract Date", "TAT in Days", "Matchkey", "Pricing.Rate per unit", "SLA_met"}),
    #"Inserted Year" = Table.AddColumn(#"Reordered Columns1", "Year", each Date.Year([Completion Date Only]), Int64.Type),
    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Year",{{"Year", "Completion_Year"}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Renamed Columns1",{"Sr. No.", "Completion Date", "Completion Date Only", "Completion_Month", "Completion_Year", "Request Type", "Request Sub-Type", "Language Type", "Batch Sr. No.", "Date of Receipt", "SOA/SOW/MOU", "Language", "Sweden/Norway/No", "Upload/Abstract Date", "TAT in Days", "Matchkey", "Pricing.Rate per unit", "SLA_met"}),
    #"Inserted Month1" = Table.AddColumn(#"Reordered Columns2", "Month", each Date.Month([#"Upload/Abstract Date"]), Int64.Type),
    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Month1",{{"Month", "Received_Month"}}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Renamed Columns2",{"Sr. No.", "Completion Date", "Completion Date Only", "Completion_Month", "Completion_Year", "Request Type", "Request Sub-Type", "Language Type", "Batch Sr. No.", "Date of Receipt", "SOA/SOW/MOU", "Language", "Sweden/Norway/No", "Upload/Abstract Date", "Received_Month", "TAT in Days", "Matchkey", "Pricing.Rate per unit", "SLA_met"}),
    #"Inserted Year1" = Table.AddColumn(#"Reordered Columns3", "Year", each Date.Year([#"Upload/Abstract Date"]), Int64.Type),
    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Year1",{{"Year", "Received_Year"}}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Renamed Columns3",{"Sr. No.", "Completion Date", "Completion Date Only", "Completion_Month", "Completion_Year", "Request Type", "Request Sub-Type", "Language Type", "Batch Sr. No.", "Date of Receipt", "SOA/SOW/MOU", "Language", "Sweden/Norway/No", "Upload/Abstract Date", "Received_Month", "Received_Year", "TAT in Days", "Matchkey", "Pricing.Rate per unit", "SLA_met"}),
    #"Renamed Columns4" = Table.RenameColumns(#"Reordered Columns4",{{"SOA/SOW/MOU", "Contract Type"}})
in
    #"Renamed Columns4"
